#!/usr/bin/env bash
# vim: set ft=sh:

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

PERLBREW_RC="$HOME/perl5/perlbrew/etc/bashrc"
[ -f "$PERLBREW_RC" ] && source "$PERLBREW_RC"
